# 문제: 카테고리 별 도서 판매량 집계하기
# URL: https://school.programmers.co.kr/learn/courses/30/lessons/144855

-- SELECT
--     B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
-- FROM 
--     BOOK B
-- JOIN 
--     BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
-- WHERE 
--     S.SALES_DATE >= TO_DATE('2022-01-01', 'YYYY-MM-DD') 
--     AND S.SALES_DATE < TO_DATE('2022-02-01', 'YYYY-MM-DD')
-- GROUP BY 
--     B.CATEGORY
-- ORDER BY 
--     B.CATEGORY;
    
SELECT
    B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM 
    BOOK B
JOIN 
    BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE 
    S.SALES_DATE >= DATE '2022-01-01' AND S.SALES_DATE < DATE '2022-02-01'
GROUP BY 
    B.CATEGORY
ORDER BY 
    B.CATEGORY;