# 문제: 카테고리 별 상품 개수 구하기
# URL: https://school.programmers.co.kr/learn/courses/30/lessons/131529

-- oracle
SELECT CATEGORY, COUNT(*) AS PRODUCTS
FROM (
        SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY
        FROM PRODUCT
    )
GROUP BY
    CATEGORY
ORDER BY CATEGORY;

-- oracle 2 _ 바로 SELECT에서 뽑아도 되는 듯
SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY
    CATEGORY
ORDER BY CATEGORY;

--mysql
SELECT SUBSTR(PRODUCT_CODE, 1, 2) as CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY
    CATEGORY
ORDER BY CATEGORY;