# 문제: 입양 시각 구하기(1)
# URL: https://school.programmers.co.kr/learn/courses/30/lessons/59412

SELECT
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS "HOUR",
    COUNT(*) AS "COUNT"
FROM
    ANIMAL_OUTS
WHERE
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
GROUP BY
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
ORDER BY
    "HOUR";

    
SELECT
    EXTRACT(HOUR FROM DATETIME) AS "HOUR",
    COUNT(*) AS "COUNT"
FROM
    ANIMAL_OUTS
WHERE
    EXTRACT(HOUR FROM DATETIME) BETWEEN 9 AND 19
GROUP BY
    EXTRACT(HOUR FROM DATETIME)
ORDER BY
    "HOUR";
    