-- 문제: 성분으로 구분한 아이스크림 총 주문량
-- URL: https://school.programmers.co.kr/learn/courses/30/lessons/133026

SELECT I.INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO I
JOIN FIRST_HALF F
    ON I.FLAVOR = F.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
